function [Rc]=RotaComp(t1,t2,t3)
Rc=[cosd(t2)*cosd(t3) sind(t1)*sind(t2)*cosd(t3)-cosd(t1)*sind(t3) cosd(t1)*cosd(t3)*sind(t2)+sind(t2)*sind(t3);...
    cosd(t2)*cosd(t3) sind(t1)*sind(t2)*sind(t3)+cos(t1)*cos(t3) cos(t1)*sind(t2)*sind(t3) -sind(t1)*cosd(t3);...
    -sind(t2) sind(t1)*cosd(t2) cosd(t1)*cosd(t2)];
end

function [Rc]=RotaCompEd(t1,t2,t3)
Rc=[cosd(t2)*cosd(t3) -cosd(t1)*sind(t3)+sind(t1)*sind(t2)*cosd(t3) sind(t1)*sind(t3)+cosd(t1)*sind(t2)*cosd(t3);...
   cosd(t2)*sind(t1) cosd(t1)*cosd(t3)+sind(t1)*sind(t2)*sind(t3) -sind(t1)*cosd(t3)+cosd(t1)*sind(t2)*sind(t3);...
    -sind(t2) sind(t1)*cosd(t2) cosd(t1)*cosd(t2)];
end

